CREATE SCHEMA IF NOT EXISTS public;
CREATE SEQUENCE IF NOT EXISTS product_id_seq;
CREATE SEQUENCE IF NOT EXISTS product_image_id_seq;
CREATE SEQUENCE IF NOT EXISTS product_id_seq;
CREATE SEQUENCE IF NOT EXISTS customer_id_seq;
CREATE SEQUENCE IF NOT EXISTS order_table_id_seq;
CREATE SEQUENCE IF NOT EXISTS orderitem_id_seq;